// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcQWW-bpqMNnt5mwmmbAThB7NiLaNRGPM',
    appId: '1:729518064880:web:e4354477c43a3418512e35',
    messagingSenderId: '729518064880',
    projectId: 'resqfood-66b5f',
    authDomain: 'resqfood-66b5f.firebaseapp.com',
    storageBucket: 'resqfood-66b5f.firebasestorage.app',
    measurementId: 'G-LDQC5GKNCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZMdL0JtG7na45y5kE764fpBrTfkPsV0',
    appId: '1:729518064880:android:6a3d9dca291e0fb5512e35',
    messagingSenderId: '729518064880',
    projectId: 'resqfood-66b5f',
    storageBucket: 'resqfood-66b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxu4ie0c-KtuKAxmsOKuq_yq-iMaeovk',
    appId: '1:729518064880:ios:eb9ec5f408f01419512e35',
    messagingSenderId: '729518064880',
    projectId: 'resqfood-66b5f',
    storageBucket: 'resqfood-66b5f.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxu4ie0c-KtuKAxmsOKuq_yq-iMaeovk',
    appId: '1:729518064880:ios:eb9ec5f408f01419512e35',
    messagingSenderId: '729518064880',
    projectId: 'resqfood-66b5f',
    storageBucket: 'resqfood-66b5f.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcQWW-bpqMNnt5mwmmbAThB7NiLaNRGPM',
    appId: '1:729518064880:web:c1d0ccf701c1e02b512e35',
    messagingSenderId: '729518064880',
    projectId: 'resqfood-66b5f',
    authDomain: 'resqfood-66b5f.firebaseapp.com',
    storageBucket: 'resqfood-66b5f.firebasestorage.app',
    measurementId: 'G-CT2LE34CTC',
  );
}
